interface OwnerSummaryData {
  overdueEnrollments: {
    parentName: string;
    parentEmail: string;
    studentName: string;
    programName: string;
    monthlyAmount: number;
    nextPaymentDue: Date;
    enrollmentId: string;
  }[];
  isFinalNotice: boolean;
  totalAmount: number;
}

export function getOwnerSummaryEmailTemplate(data: OwnerSummaryData): string {
  const formattedTotal = data.totalAmount.toFixed(2);

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>STEM Masters - ${data.isFinalNotice ? 'Suspended' : 'Overdue'} Enrollments Summary</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
        }
        .header {
          background-color: ${data.isFinalNotice ? '#d32f2f' : '#f57c00'};
          color: white;
          padding: 20px;
          text-align: center;
          border-radius: 8px 8px 0 0;
        }
        .content {
          background-color: #ffffff;
          padding: 30px;
          border: 1px solid #e0e0e0;
          border-radius: 0 0 8px 8px;
        }
        .summary-table {
          width: 100%;
          border-collapse: collapse;
          margin: 20px 0;
        }
        .summary-table th,
        .summary-table td {
          border: 1px solid #ddd;
          padding: 12px;
          text-align: left;
        }
        .summary-table th {
          background-color: #f5f5f5;
          font-weight: bold;
        }
        .summary-table tr:nth-child(even) {
          background-color: #f9f9f9;
        }
        .total-box {
          background-color: #ffecb3;
          border-left: 4px solid #ffa000;
          padding: 15px;
          margin: 20px 0;
          text-align: center;
        }
        .footer {
          margin-top: 30px;
          text-align: center;
          font-size: 12px;
          color: #666;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>STEM Masters - Owner Dashboard</h1>
        <h2>${data.isFinalNotice ? 'Suspended Enrollments' : 'Overdue Payments'} Summary</h2>
      </div>
      
      <div class="content">
        <h3>Summary Report - ${new Date().toLocaleDateString()}</h3>
        
        <div class="total-box">
          <h3>Total ${data.isFinalNotice ? 'Suspended' : 'Overdue'} Amount: $${formattedTotal}</h3>
          <p>Number of Enrollments: ${data.overdueEnrollments.length}</p>
        </div>
        
        ${data.isFinalNotice ? `
        <p><strong>The following enrollments have been suspended due to overdue payments:</strong></p>
        ` : `
        <p><strong>The following enrollments have overdue payments:</strong></p>
        `}
        
        <table class="summary-table">
          <thead>
            <tr>
              <th>Parent Name</th>
              <th>Parent Email</th>
              <th>Student Name</th>
              <th>Program</th>
              <th>Monthly Amount</th>
              <th>Due Date</th>
              <th>Enrollment ID</th>
            </tr>
          </thead>
          <tbody>
            ${data.overdueEnrollments.map(enrollment => `
            <tr>
              <td>${enrollment.parentName}</td>
              <td><a href="mailto:${enrollment.parentEmail}">${enrollment.parentEmail}</a></td>
              <td>${enrollment.studentName}</td>
              <td>${enrollment.programName}</td>
              <td>$${enrollment.monthlyAmount.toFixed(2)}</td>
              <td>${enrollment.nextPaymentDue.toLocaleDateString()}</td>
              <td>${enrollment.enrollmentId}</td>
            </tr>
            `).join('')}
          </tbody>
        </table>
        
        <h3>Actions Taken</h3>
        <ul>
          <li>Individual ${data.isFinalNotice ? 'final notice' : 'overdue payment'} emails sent to all parents</li>
          ${data.isFinalNotice ? '<li>Enrollments marked as suspended in the system</li>' : ''}
          <li>This summary report generated for administrative review</li>
        </ul>
        
        <h3>Recommended Next Steps</h3>
        <ul>
          <li>Follow up with parents who have not responded</li>
          <li>Review payment plans for families experiencing difficulties</li>
          ${data.isFinalNotice ? '<li>Coordinate with instructors about suspended students</li>' : '<li>Monitor for payments over the next few days</li>'}
          <li>Update enrollment statuses as payments are received</li>
        </ul>
        
        <p>This automated report was generated by the STEM Masters payment monitoring system.</p>
      </div>
      
      <div class="footer">
        <p>&copy; ${new Date().getFullYear()} STEM Masters. All rights reserved.</p>
        <p>This is an automated administrative report.</p>
      </div>
    </body>
    </html>
  `;
}